nodeLinker: node-modules

packageExtensions:
  react-native-codegen@*:
    peerDependencies:
      "@babel/preset-env": "*"
  react-native@*:
    peerDependencies:
      "@babel/preset-env": "*"
    peerDependenciesMeta:
      "@babel/preset-env":
        optional: true

yarnPath: .yarn/releases/yarn-3.2.3.cjs
