nodeLinker: node-modules

packageExtensions:
  react-native@*:
    peerDependencies:
      "@babel/preset-env": "*"
    peerDependenciesMeta:
      "@babel/preset-env":
        optional: true
  react-native-codegen@*:
    peerDependencies:
      "@babel/preset-env": "*"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
