nodeLinker: node-modules

packageExtensions:
  react-native-animated-pagination-dot@*:
    peerDependenciesMeta:
      "react-dom":
        optional: true
  react-native-codegen@*:
    peerDependencies:
      "@babel/preset-env": "*"
  react-native@*:
    peerDependencies:
      "@babel/preset-env": "*"
    peerDependenciesMeta:
      "@babel/preset-env":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
